name: csharp-tests

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  generate-and-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install tools
        run: |
          npm install -g @stoplight/prism-cli @getgauge/cli @openapitools/openapi-generator-cli
          sudo apt install shunit2 -y

      - name: Test csharp codegen
        run: FILTER="testGoCodegen" ./test_codegen.sh
        working-directory: tests
