name: java-tests

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  generate-and-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '24'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.14

      - name: Install tools
        run: |
          npm install -g @stoplight/prism-cli @getgauge/cli @openapitools/openapi-generator-cli
          sudo apt install shunit2 -y

      - name: Test java codegen
        run: FILTER="testJavaCodegen*" ./test_codegen.sh
        working-directory: tests
