name: java-tests

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  generate-and-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.24.0'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '24'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.14

      - name: Install npm tools
        run: npm install -g @stoplight/prism-cli @getgauge/cli @openapitools/openapi-generator-cli

      - name: Install shUnit2
        run: sudo apt install shunit2 -y

      - name: Install jd
        run: go install github.com/josephburnett/jd/v2/jd@v2.3.0

      - name: Test java codegen
        run: ./test_codegen.sh --filter testJavaCodegen*
        working-directory: tests
