name: python-tests

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  generate-and-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install tools
        run: |
          npm install -g @stoplight/prism-cli @getgauge/cli @openapitools/openapi-generator-cli
          sudo apt install shunit2 -y

      - name: Test python codegen
        run: FILTER="testPythonCodegen" ./test_codegen.sh
        working-directory: tests
