name: typescript-node-tests

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  generate-and-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: |
          npm install -g @stoplight/prism-cli @getgauge/cli @openapitools/openapi-generator-cli
          sudo apt install shunit2 -y

      - name: Test typescript-node codegen
        run: FILTER="testTypeScriptNodeCodegen" ./test_codegen.sh
        working-directory: tests
